
sogecommerce_sylius_account_customer_wallet:
  path: /{_locale}/sogecommerce/account/customer-wallet
  methods: [POST, GET]
  defaults:
    _controller: 'Lyranetwork\Sogecommerce\Controller\CustomerWalletController::savedCardsAction'