sylius_twig_hooks:
  hooks:
    base_lyra_fields: &lyra_fields
      lyra_rest_api_widget:
          template: '@LyranetworkLyraPlugin/admin/payment_method/form/lyra_rest_api_widget.html.twig'
          priority: 0
      lyra_rest_api_check_url:
        template: '@LyranetworkLyraPlugin/admin/payment_method/form/lyra_rest_api_check_url.html.twig'
        priority: 0

    'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.lyra_sylius_payment':
      <<: *lyra_fields

    'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.lyra_sylius_payment':
      <<: *lyra_fields

    'sylius_admin.order.show.content.sections.payments.item':
      name:
        template: '@LyranetworkLyraPlugin/admin/order/payment_details.html.twig'
        priority: 150
    'sylius_admin.payment_method.create.content.form.sections':
      general:
        template: '@LyranetworkLyraPlugin/admin/payment_method/general.html.twig'
        priority: 150
    'sylius_admin.payment_method.update.content.form.sections':
      general:
        template: '@LyranetworkLyraPlugin/admin/payment_method/general.html.twig'
        priority: 150