sylius_twig_hooks:
  hooks:
    'sylius_shop.checkout.select_payment.content.form.select_payment.payment.choice.lyra_sylius_payment':
      details:
        template: '@LyranetworkLyraPlugin/shop/checkout/select-payment/lyra_choice.html.twig'
        priority: 150
    'sylius_shop.order.show.content.form.select_payment.payment.choice.lyra_sylius_payment':
      details:
        template: '@LyranetworkLyraPlugin/shop/checkout/select-payment/lyra_choice.html.twig'
        priority: 150
    'sylius_shop.account.lyra.saved_cards.index.content.main':
      section:
        template: '@LyranetworkLyraPlugin/shop/account/saved_cards/section.html.twig'
        priority: 150