
payzen_sylius_account_customer_wallet:
  path: /{_locale}/payzen/account/customer-wallet
  methods: [POST, GET]
  defaults:
    _controller: 'Lyranetwork\Payzen\Controller\CustomerWalletController::savedCardsAction'