sylius_twig_hooks:
  hooks:
    base_systempay_fields: &systempay_fields
      systempay_rest_api_site_id:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_rest_api_site_id.html.twig'
        priority: 0
      systempay_rest_api_mode:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_rest_api_mode.html.twig'
        priority: 0
      systempay_rest_api_rest_check_url:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_rest_api_rest_check_url.html.twig'
        priority: 0
      systempay_rest_api_private_test_key:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_rest_api_private_test_key.html.twig'
        priority: 0
      systempay_rest_api_private_prod_key:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_rest_api_private_prod_key.html.twig'
        priority: 0
      systempay_rest_api_public_test_key:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_rest_api_public_test_key.html.twig'
        priority: 0
      systempay_rest_api_public_prod_key:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_rest_public_prod_key.html.twig'
        priority: 0
      systempay_rest_api_hmac_test_key:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_rest_api_hmac_test_key.html.twig'
        priority: 0
      systempay_rest_api_hmac_prod_key:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_rest_api_hmac_prod_key.html.twig'
        priority: 0
      systempay_advanced_options_card_data_entry_mode:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_advanced_options_card_data_entry_mode.html.twig'
        priority: 0
      systempay_advanced_options_rest_theme:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_advanced_options_rest_theme.html.twig'
        priority: 0
      systempay_advanced_options_rest_attempts:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_advanced_options_rest_attempts.html.twig'
        priority: 0
      systempay_advanced_options_rest_popin_mode:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_advanced_options_rest_popin_mode.html.twig'
        priority: 0
      systempay_advanced_options_rest_compact_mode:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_advanced_options_rest_compact_mode.html.twig'
        priority: 0
      systempay_advanced_options_oneclick_payment:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_advanced_options_oneclick_payment.html.twig'
        priority: 0
      systempay_payment_options_capture_delay:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_payment_options_capture_delay.html.twig'
        priority: 0
      systempay_payment_options_validation_mode:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/form/systempay_payment_options_validation_mode.html.twig'
        priority: 0

    'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.systempay_sylius_payment':
      <<: *systempay_fields

    'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.systempay_sylius_payment':
      <<: *systempay_fields

    'sylius_admin.order.show.content.sections.payments.item':
      name:
        template: '@LyranetworkSystempayPlugin/admin/order/payment_details.html.twig'
        priority: 150
    'sylius_admin.order.show.content.sections.payments.item.actions':
      refund:
        template: '@LyranetworkSystempayPlugin/admin/order/payment_action_refund.html.twig'
        priority: 150
    'sylius_admin.payment_method.create.content.form.sections':
      general:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/general.html.twig'
        priority: 150
    'sylius_admin.payment_method.update.content.form.sections':
      general:
        template: '@LyranetworkSystempayPlugin/admin/payment_method/general.html.twig'
        priority: 150