sylius_twig_hooks:
  hooks:
    'sylius_shop.checkout.select_payment.content.form.select_payment.payment.choice.systempay_sylius_payment':
      details:
        template: '@LyranetworkSystempayPlugin/shop/checkout/select-payment/systempay_choice.html.twig'
        priority: 150
    'sylius_shop.order.show.content.form.select_payment.payment.choice.systempay_sylius_payment':
      details:
        template: '@LyranetworkSystempayPlugin/shop/checkout/select-payment/systempay_choice.html.twig'
        priority: 150
    'sylius_shop.account.systempay.saved_cards.index.content.main':
      section:
        template: '@LyranetworkSystempayPlugin/shop/account/saved_cards/section.html.twig'
        priority: 150