monetico_sylius_account_customer_wallet:
  path: /{_locale}/monetico/account/customer-wallet
  methods: [POST, GET]
  defaults:
    _controller: 'Lyranetwork\Monetico\Controller\CustomerWalletController::savedCardsAction'

monetico_rest_configuration_widget_token:
  path: /monetico/rest/configuration/widget-token
  methods: [POST]
  defaults:
    _controller: 'Lyranetwork\Monetico\Controller\RestConfigurationController::getWidgetToken'

monetico_rest_configuration_default_form_configuration:
  path: /monetico/rest/configuration/default-config
  methods: [GET]
  defaults:
    _controller: 'Lyranetwork\Monetico\Controller\RestConfigurationController::getDefaultConfiguration'
