
monetico_sylius_account_customer_wallet:
  path: /{_locale}/monetico/account/customer-wallet
  methods: [POST, GET]
  defaults:
    _controller: 'Lyranetwork\Monetico\Controller\CustomerWalletController::savedCardsAction'