lyra_return_url:
  path: /lyra/rest/return
  methods: [POST, GET]
  defaults:
    _controller: 'Lyranetwork\Lyra\Controller\OrderController::paymentResponseAction'

lyra_rest_ipn:
  path: /lyra/rest/ipn
  methods: [POST, GET]
  defaults:
    _controller: 'Lyranetwork\Lyra\Controller\OrderController::paymentResponseAction'

lyra_payment_refund:
  path: /lyra/orders/{orderId}/payments/{id}/refund
  methods: [PUT, POST]
  defaults:
    _controller: 'Lyranetwork\Lyra\Controller\RefundController::paymentRefundOrCancelAction'

lyra_sylius_account_saved_cards:
  path: /{_locale}/lyra/account/saved-cards
  methods: [POST, GET]
  defaults:
    _controller: 'Lyranetwork\Lyra\Controller\CardController::savedCardsAction'