sylius_twig_hooks:
  hooks:
    'sylius_shop.account.monetico.customer_wallet.index.content.main':
      section:
        template: '@LyranetworkMoneticoPlugin/shop/account/customer_wallet/section.html.twig'
        priority: 150